config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root 'home#index'
  get 'contact', to: 'single_pages#contact'
  get 'concept', to: 'single_pages#concept'
  get 'team', to: 'single_pages#team'
  
 

  resources :ingredients, only: [:index] 
  resources :menu_recipes, only: [:create, :destroy] do 
    get :autocomplete_recipe_name, :on => :collection
  end

  resources :recipes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get :autocomplete_ingredient_name, :on => :collection
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :pictures, only: [:create, :show]
  end
  
  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :avatars, only: [:create]
    resources :menus, only: [:show, :destroy, :update] do 
      resources :shopping_lists, only: [:show,:create]
    end
  end

  resources :recipe_categories, only: [:show] 

  namespace :admin do 
    resources :recipes, only: [:index, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :comments, only: [:destroy]
  end
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  before_save :default_values
    
  belongs_to :recipe_category
  belongs_to :user
  has_many :users, through: :likes
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  has_many :menu_recipes, dependent: :destroy
  has_many :menus, through: :menu_recipes
  has_many :compositions, dependent: :destroy
  has_many :ingredients, through: :compositions
  has_many :likes, dependent: :destroy
  has_one_attached :picture

  validates :name, presence: true
  validates :description, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :price_indicator, presence: true
  validates :recipe_category_id, presence: true

  before_create :default_picture

  default_scope { order(created_at: :desc) }

  def default_picture
    self.picture.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'default_recipe.jpg')), filename: 'default_recipe.jpg', content_type: 'image/jpg')
  end 
  
  def get_ingredients_number_from_new_recipe_form(params)
    ingredients  = []
    params.each do |ingredient|
      if ingredient != '0'
        ingredients << ingredient.to_i
      end
    end
    return ingredients
  end
  
  def translate_input_ingredients_into_database_ingredients_ids(params)
    selected_ingredients = params.split(', ') # je récupère les ingrédients sélectionnés en splittant à chaque espace
    selected_ingredients_objects = [] # initialisation du tableau qui va contenir les ids d'ingrédients
    selected_ingredients.each do |ingredient_name| # pour chaque nom d'ingrédient entré dans ma barre de recherche
      Ingredient.all.each do |ingredient| # et pour chaque ingrédient présent dans ma BDD
        if ingredient_name == ingredient.name # je compare l'entrée avec les noms
          selected_ingredients_objects << ingredient # s'il existe, j'enregistre l'id
        end
      end
    end
      return selected_ingredients_objects
  end

  def find_recipes_associated_with_ingredients(ingredients)
    all_recipes = Recipe.where(is_displayed: true)
    matching_recipes = []
    all_recipes.each do |recipe|
      if (ingredients - recipe.ingredients).empty? 
        matching_recipes << recipe
      end
    end
    return matching_recipes
  end  

  def picture_300
    return self.picture.variant(resize: '300x300')
  end  

  def default_values
    self.is_displayed ||= false
  end
  
end

app/controllers/admin/recipes_controller.rb
class Admin::RecipesController < ApplicationController
  before_action :check_if_admin!
  
  def index
    @recipes = Recipe.all.sort
  end
    
  def edit
    @recipe = Recipe.find(params[:id])
    @recipe_categories = []
    RecipeCategory.all.each do |recipe|
      @recipe_categories << [recipe.name, recipe.id]
    end
    @price_indicators = [["€", 1], ["€ €", 2], ["€ € €", 3], ["€ € € €", 4], ["€ € € € €",5]]
  end 

  
  def update
      @recipe = Recipe.find(params[:id])
    if params[:recipe]
      @recipe.update(update_params)
      
      flash[:success] = "La recette a bien été modifiée !"
      redirect_to admin_recipes_path
    else
      @recipe.is_displayed = !@recipe. is_displayed
      @recipe.save
    
      flash[:success] = "Le statut de la recette #{@recipe.id} a bien été modifié !"
      redirect_to admin_recipes_path
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    redirect_to admin_recipes_path
  end
  
  private 

  def update_params
    params[:recipe].permit(:name, :recipe_category_id, :price_indicator, :cooking_time, :preparation_time, :description)
  end

  def check_if_admin!
    if user_signed_in?
      if current_user.is_admin == false
        flash[:error] = "Accès réservé aux meilleurs cuisiniers !"
        redirect_to root_path
      end
    else
      flash[:error] = "Accès réservé aux meilleurs cuisiniers !"
      redirect_to root_path
    end
  end


end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new]
  before_action :is_my_recipe!, only: [:edit, :update]
  autocomplete :ingredient, :name, :display_value => :funky_method

  def index
    recipe = Recipe.new
    
    unless params[:ingredient].to_s.empty? 

      selected_ingredients = recipe.translate_input_ingredients_into_database_ingredients_ids(params[:ingredient])
      @recipes = recipe.find_recipes_associated_with_ingredients(selected_ingredients)
    else
      @recipes = all_recipes_displayable
    end

    @menu_recipe = MenuRecipe.new
  end
    
  def show
    @recipe = Recipe.find(params[:id])
    @comments = Comment.where(recipe_id: @recipe.id)
    @comment = Comment.new
    @compositions = Composition.where(recipe_id: @recipe.id)
  end 

  def new 
    @recipe = Recipe.new
    @recipe_categories = RecipeCategory.all
    @ingredients = Ingredient.all
    @price_indicators = ["€", "€ €", "€ € €", "€ € € €", "€ € € € €"]
  end

  def create
    @recipe = Recipe.new(
      name: params[:name], 
      description: params[:description], 
      recipe_category_id: params[:recipe_category].to_i,
      price_indicator: params[:price_indicator].to_i, 
      cooking_time: params[:cooking_time], 
      preparation_time: params[:preparation_time], 
      user_id: current_user.id)
      ingredients_ids = params[:ingredient_ids]

    if @recipe.save
        @recipe.picture.attach(params[:picture])
        ingredients_ids.each do |ingredient_id|
          params[:quantities].each do |key, value|
            if ingredient_id == key 
              composition = Composition.new(recipe_id: @recipe.id, ingredient_id: ingredient_id.to_i, quantity: value.to_i)
              composition.save 
            end
          end
        end
      flash[:success] = "Ta recette a bien été sauvegardée !"

      redirect_to recipe_path(@recipe.id)
    else 
      flash[:error] = "Désolé, ta recette n'a pas été sauvegardée !"

      redirect_to new_recipe_path
    end
  end

    
  def edit
    @recipe = Recipe.find(params[:id])
    @recipe_categories = []
    RecipeCategory.all.each do |recipe|
      @recipe_categories << [recipe.name, recipe.id]
    end
    @price_indicators = [["€", 1], ["€ €", 2], ["€ € €", 3], ["€ € € €", 4], ["€ € € € €",5]]
  end 

  def update
    @recipe = Recipe.find(params[:id])
    @recipe.update(update_params)
    
    redirect_to recipe_path(@recipe)
  end

  def destroy
    @recipe = Recipe.where(user_id: params[:id])
    @recipe.user_id = 2
  end
  
  private

  def post_params
    params.require(:recipe).permit(:ingredient, :picture)
  end

  def included_in?(array)
    array.to_set.superset?(self.to_set)
  end

  def update_params
    params[:recipe].permit(:name, :recipe_category, :price_indicator, :preparation_time, :cooking_time, :description)
  end

  def is_my_recipe!
    if Recipe.find(params[:id]).user_id != current_user.id
      flash[:error]= "On ne modifie pas ce qui ne nous appartient pas !"

      redirect_to root_path
    end
  end

end

app/helpers/admin/recipes_helper.rb
module Admin::RecipesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

  def is_current_user_the_creator(recipe)
    if user_signed_in?
      if current_user.id == recipe.user_id
        return true
      end
    end
  end

end

app/views/recipes/_main_picture_edit.html.erb
<h3>Changer d'avatar ?</h3>
<p><%= form_tag recipe_pictures_path(@recipe), multipart: true do %>
  <%= file_field_tag :picture%>
  <%= submit_tag "Mettre à jour" %>
<% end %>

</p>

app/views/recipes/_picture.html.erb
<h3> Ajouter la photo de la recette</h3>

<p>
  <%= form_tag do %>
  <%= file_field_tag :picture %>
  <%= submit_tag "Valider la photo" %>
<% end %>
  </p>
</div>

app/views/recipes/_picture_edit.html.erb
<h3>Changer d'avatar ?</h3>
<p><%= form_tag recipe_pictures_path(@recipe), multipart: true do %>
  <%= file_field_tag :picture%>
  <%= submit_tag "Mettre à jour" %>
<% end %>

</p>

app/views/recipes/_recipe.html.erb
<div class="col-sm-6 col-md-4 px-2 pb-3">
  
  <%= link_to recipe_path(recipe) do %>
    <%if recipe.picture.attached? %>
      <div class="container-pic-index">
        <%= image_tag recipe.picture_300, class:"w-100 img-fluid rounded" %>
      </div>
    <%else%>
      <div class="container-pic-index">
        <%= image_tag "the-creative-exchange-1309304-unsplash", class:"w-100 img-fluid rounded" %>
      </div>
    <%end%>
  <% end %>

  <div class="recipe-info py-3">  

    <%= link_to recipe_path(recipe), class: "title h4 mr-2" do %>
      <%= recipe.name %>
    <% end %>
  
    <div class="the-icons my-2 text-grey1 h6 font-weight-normal">

    <span class="mr-3">
      <% if recipe.recipe_category.id == 1 %>
        <i class="fas fa-drumstick-bite text-omnivore " data-toggle="tooltip" data-placement="top" title="Omnivore"></i>
      <% elsif recipe.recipe_category.id == 2 %>
        <i class="fas fa-cheese text-vegetarian" data-toggle="tooltip" data-placement="top" title="Végétarien"></i>
      <% elsif recipe.recipe_category.id == 3 %>
        <i class="fas fa-seedling text-vegan" data-toggle="tooltip" data-placement="top" title="Végétalien"></i>
      <% end %>
    </span>

      <span class="mr-3">
        <i class="fas fa-tag mr-1"></i> <%recipe.price_indicator.times do %>€<%end%>
      </span>
      <span class="mr-3">
        <i class="far fa-comment mr-1"></i> <%= recipe.comments.count %>
      </span>
      <span class="mr-3"> 
        <% if user_signed_in?%>
          <% pre_like = recipe.likes.find { |like| like.user_id == current_user.id} %>
            <% if pre_like %>
              <%= link_to recipe_like_path(recipe, pre_like), method: :delete do %>
              <i class="fas fa-heart mr-1"></i>
            <% end %>
            <% else %>
                <%= link_to recipe_likes_path(recipe), method: :post do %>
                <i class="far fa-heart mr-1"></i>
              <% end %>
            <% end %>
          <%= recipe.likes.count %> <%= (recipe.likes.count) == 1 ? '' : ''%>
          <% else %>
            <i class="far fa-heart mr-1"></i> <%= recipe.likes.count %>
        <% end %>

      </span>
    </div>
    
    <div class="recipe-links mt-3 m">
      <%=link_to "Voir la recette", recipe_path(recipe), class:"recipe-link btn btn-outline-primary px-3 mb-2" %>
      <%if user_signed_in?%>
          <%= link_to menu_recipes_path(menu_id: Menu.where(user_id: current_user.id).last.id, recipe_id: recipe.id), class:"recipe-link btn btn-primary px-3 mb-2", method: "post" do %>
          <i class="fas fa-plus mr-1"></i> Ajouter à mon menu
          <% end %>
      <% end%>
    </div>
  </div>
</div>

app/views/recipes/_recipe_comments.html.erb
<div class="block block-900 bg-grey5 p-4 p-md-5 rounded-top">
  <h3 class="text-center mb-3"><i class="far fa-comments mr-2"></i>
    <% if @comments.empty? %>
      Il n'y a aucun avis sur cette recette 
    <% else %>
      <%= @comments.count %> avis sur cette recette
    <% end %>
  </h3>
  <% @comments.each do |comment|%>
    <div class="container-comment mb-3 mr-0">
      <div class="row">
        <div class="col-3 col-sm-2 pr-2 pr-md-0">
          <div class="avatar-comments">
            <%if comment.user.avatar.attached? %>
              <%= image_tag comment.user.avatar, alt: 'avatar', class: 'w-100' %>
            <% else %>
              <%= image_tag comment.user.default_image, alt: 'avatar', class: 'w-100' %>
            <% end %>
          </div>
        </div>
        <div class="col-9 col-sm-10 pl-2 pl-md-0">
          <div class="bg-white p-3 rounded">
            <h5 class="h6 text-grey1 mb-0"><i class="fas fa-at"></i>
              <% if comment.user.nickname == nil %>
                A définir
              <% else %>
                <%= comment.user.nickname %>
              <% end %>
            </h5>
            <p class="mb-2"><small class="text-grey2">Posté le <%= comment.created_at.strftime("%A, %d %b %Y %l:%M %p") %></small></p> 
            <p class="mb-0 pb-2"><%= comment.description %></p>
            <%if user_signed_in?%>
              <% if current_user == comment.user %>
                <%= link_to recipe_comment_path(@recipe, comment_id: comment.id), method: 'delete', class:'text-danger' do %>
                  <i class="far fa-trash-alt mr-2"></i>Supprimer
                <% end %>
              <% elsif current_user.is_admin == true %>
                  <%= link_to admin_comment_path(comment, recipe_id: params[:id]), method: 'delete', class:'text-danger' do %>
                    <i class="far fa-trash-alt mr-2"></i>Supprimer
                  <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% if user_signed_in? %>
<div class="block block-900 container-comment p-4 p-md-5 rounded-bottom bg-secondary">
  <h3 class="text-center text-white text-center mb-3"><i class="fas fa-comment"></i> Ajouter un avis</h3>
  <%= form_with model: @comment, url:recipe_comments_path(@recipe.id) do |form| %>
  <%= form.text_area :description, rows: 6, class:"form-control", placeholder: "Ton message" %><br>
  <div class="text-center">
    <%= form.submit "Envoyer", class: "btn btn-primary btn-lg px-5" %>
  </div>
  <% end %>
</div>
<% end %>

app/views/recipes/_recipe_content.html.erb
<div class="block block-900 bg-white text-center rounded mb-4 mb-lg-5 py-5">

  <header class="recipe-title mb-3 mb-md-4">
    <h1 class="h2 mb-0">
      <%= @recipe.name%>

     
      
    </h1>
    <p>Recette proposée par <span class="font-weight-bold"><%= @recipe.user.first_name %></span></p>
  </header>


  <div class="row mb-4">
    <div class="col-12 col-md-8 pr-md-0">
      <div class="container-pic">
        <%if @recipe.picture.attached? %>
          <%= image_tag @recipe.picture, class:"w-100 rounded" %>
        <%else%>
          <%= image_tag @recipe.default_recipe, class:"w-100 rounded" %>
        <%end%>
      </div>
    </div>

    <div class="col-12 col-md-4 pl-md-0">
      <div class="bg-dark p-4 h-100 rounded">
        <div class="the-icons text-white text-left h4 font-weight-normal">
          <ul class="list-unstyled">
            <li class="mb-2 h2 text-white">
            <% if user_signed_in?%>
              <% pre_like = @recipe.likes.find { |like| like.user_id == current_user.id} %>
              <% if pre_like %>
                <%= link_to recipe_like_path(@recipe, pre_like), method: :delete do %>
                  <i class="fas fa-heart mr-1"></i>
                <% end %>
              <% else %>
                <%= link_to recipe_likes_path(@recipe), method: :post do %>
                  <i class="far fa-heart mr-1"></i>
                <% end %>
              <% end %>
              <%= @recipe.likes.count %> <%= (@recipe.likes.count) == 1 ? '' : ''%>
              <% else %>
                <i class="far fa-heart mr-1"></i> <%= @recipe.likes.count %>
            <% end %>
            </li>

            <li class="mb-2">
              <span class="h6 text-indigo2">Catégorie</span><br>
                <% if @recipe.recipe_category.id == 1 %>
                  <span class="h5 text-omnivore"><i class="fas fa-drumstick-bite text-omnivore " data-toggle="tooltip" data-placement="top" title="Omnivore"></i> Omnivore</span>
                <% elsif @recipe.recipe_category.id == 2 %>
                  <span class="h5 text-vegetarian"><i class="fas fa-cheese text-vegetarian" data-toggle="tooltip" data-placement="top" title="Végétarien"></i> Végétarien</span>
                <% elsif @recipe.recipe_category.id == 3 %>
                  <span class="h5 text-vegan"><i class="fas fa-seedling text-vegan" data-toggle="tooltip" data-placement="top" title="Végétalien"></i> Végétalien</span>
                <% end %>
              </span>
            </li>
            <li class="mb-2">
              <span class="h6 text-indigo2">Temps de préparation</span><br>
              <span class="h5 text-indigo4"><i class="far fa-clock mr-1"></i></span> <%=@recipe.preparation_time%> mn
            </li>
            <li class="mb-2">
              <span class="h6 text-indigo2">Temps de cuisson</span><br>
              <span class="h5 text-indigo4"><i class="far fa-clock mr-1"></i></span> <%=@recipe.cooking_time%> mn
            </li>
            <li class="mb-4">
              <span class="h6 text-indigo2">Tranche de prix</span><br>
                <span class="h5 text-indigo4"><i class="fas fa-tag mr-1"></i></span> <%@recipe.price_indicator.times do %>€
                <%end%>
            </li>
            <li class="mb-4">
              <%if user_signed_in? %>

                <%= link_to menu_recipes_path(menu_id: Menu.where(user_id: current_user.id).last.id, recipe_id: @recipe.id), class:"recipe-link btn btn-primary py-2 w-100 text-uppercase", method: "post" do %>
                Ajouter à mon<br> <span class="h5 text-white">menu</span>
                <% end %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <article class="recipe-content text-left mb-5">

    <% if is_current_user_the_creator(@recipe) %>
      <div class="p-3 p-md-4 bg-grey5 rounded border border-indigo5 mb-4">
      <h5 class="text-secondary">Modifier la photo de recette</h5>
        <% if is_current_user_the_creator(@recipe) %> 
          <%= form_tag recipe_pictures_path(@recipe), multipart: true do %>
            <%= file_field_tag :picture %>
            <%= submit_tag "Mettre à jour", class: "btn btn-outline-primary ml-2" %>
          <% end %>
        <% end %>
      </div>
    <% end %>
    
    <div class="row">
      <div class="col-12">
        <div class="ingredients p-4 p-md-5 bg-grey5 rounded mb-4">
          <h3 class="h4">Ingrédients pour une personne</h3>
          <ul>
          <% @compositions.each do |composition| %>
            <li> <%= composition.ingredient.name %> : <%= composition.quantity %> <%= composition.ingredient.unit %></li>
          <% end %>
          </ul>
        </div> 
      </div>

      <div class="col-12">
        <div class="preparation p-4 p-md-5 border border-grey3 rounded">
          <h3 class="h4">Préparation</h3>
          <%= simple_format(@recipe.description) %> <br>
        </div>
      </div>
    </div>
    
  </article>

  <%= link_to "Voir les autres recettes", recipes_path(@recipes), class: 'btn btn-outline-primary btn-lg' %>

  <% if is_current_user_the_creator(@recipe) %>
    <%= link_to "Editer la recette", edit_recipe_path(@recipe), class: 'btn btn-outline-danger btn-lg' %>
  <% end %>

</div>

app/views/recipes/edit.html.erb
<div class="bg-container" id="contact">
  <div class="block block-800 p-4 p-md-5 bg-white rounded">
    <header class="block block-800 p-4 p-md-5 text-center">
      <h2>Editer la recette n° <%= @recipe.id %></h2>
      <p class="intro">Après plusieurs essais, vous voulez améliorer la recette ? C'est l'endroit ! </p>
    </header>


    <%= form_for @recipe do |f| %>

      <div class="form-group mb-4">
        <label>Nom de la recette</label>
         <%= f.text_field :name, class: 'form-control mb-3' %>
      </div>

      <div class="form-row mb-4">
        <div class="col-12 col-md-6 mb-4 mb-md-0">
        <label>Catégorie <small>(régime alimentaire)</small></label><br>
        <%= f.select :recipe_category_id do %>
          <% @recipe_categories.each do |category| -%>
            <%= content_tag(:option, category.first, value: category.last) %>
          <% end %>
        <% end %>
        </div>
        <div class="col-12 col-md-6">
        <label>Catégorie <small>(Sélectionner une tranche de prix)</small></label>
        <%= f.select :price_indicator, prompt: "Sélectionner" do %>
          <% @price_indicators.each do |price| -%>
            <%= content_tag(:option, price.first, value: price.last) %>
          <% end %>
        <% end %>
        </div>
      </div>

      <div class="form-row mb-4">
        <div class="col-12 col-md-6">
          <label>Temps de cuisson <small>(en minutes)</small></label>
          <%= f.number_field :cooking_time, class:"form-control" %>
        </div>
        <div class="col-12 col-md-6">
          <label>Temps de préparation <small>(en minutes)</small></label>
          <%= f.number_field :preparation_time, class:"form-control" %>
        </div>
      </div>

      <div class="form-group mb-4">
        <label>Description <small>(Sélectionner une tranche de prix)</small></label>
        <%= f.text_area :description, class:"form-control", rows: 16 %>
      </div>

      <div class="form-group mb-4 text-center">
        <%= f.submit "Modifier la recette", class:"btn btn-primary btn-lg" %>
      </div>

    <% end %>
      
  </div>
</div>

app/views/recipes/index.html.erb
<div class="bg-container" id="index-recipes">

  <div class="block block-1000 bg-white p-4 p-md-5 border-bottom rounded-top text-center">
    <h2 class="text-secondary">Les recettes</h2>
    <h4 class='text-grey1 font-weight-normal'>Il y a <%= @recipes.count %> recettes disponibles</h4>
  </div>

  <div class="block block-1000 bg-white rounded-bottom py-lg-5"> 
    <div class="row">
      <%= render @recipes %>
    </div>
  </div>

</div>
  

app/views/recipes/new.html.erb
<div class="bg-container" id="contact">
  <div class="block block-800 p-4 p-md-5 bg-white rounded">
    <header class="block block-800 p-4 p-md-5 text-center">
      <h2>Proposer une nouvelle recette</h2>
      <p class="intro">Vous avez une idée de recette que vous souhaiteriez proposer à la communauté des Batch-Cookerz ? Vous êtes au bon endroit :)</p>
    </header>
    <%= form_tag url_for(action: 'create'), method: "post", multipart: true, class: "needs-validation" do %>
      <div class="form-group mb-4">
        <%= label_tag 'Nom de la recette', nil, class:"font-weight-bold text-secondary" %>
        <%= text_field_tag :name, "", class: 'form-control' %>
      </div>
      <div class="form-row mb-4">
        <div class="col-12 col-md-6">
          <%= label_tag 'Catégorie', nil, class:"font-weight-bold text-secondary" %> <small class="text-grey1">(Régime alimentaire)</small>
          <%= select_tag :recipe_category, options_from_collection_for_select(@recipe_categories, "id", "name"), prompt: "Sélectionner", class:"form-control" %>
        </div>
        <div class="col-12 col-md-6">
          <%= label_tag 'Prix', nil, class:"font-weight-bold text-secondary" %> <small class="text-grey1">(Sélectionner une tranche de prix)</small>
          <%= select_tag :price_indicator, options_for_select([['€',1],['€€',2],['€€€',3],['€€€€',4],['€€€€€',5]]), prompt: "Sélectionner", class:"form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= label_tag 'Description', nil, class:"font-weight-bold text-secondary" %> <small class="text-grey1">(2000 caractères maximum)</small>
        <%= text_area_tag :description, "", rows: 6, class: "form-control" %>
      </div>
      <div class="form-row mb-4">
        <div class="col-12 col-md-6">
          <%= label_tag 'Temps de préparation', nil, class:"font-weight-bold text-secondary" %> <small class="text-grey1">(en minutes)</small>
          <%= number_field_tag :preparation_time, "", class: "form-control" %>
        </div>
        <div class="col-12 col-md-6">
          <%= label_tag 'Temps de cuisson', nil, class:"font-weight-bold text-secondary" %> <small class="text-grey1">(en minutes)</small>
          <%= number_field_tag :cooking_time, "", class: "form-control" %>
        </div>
      </div>
      <div class="form-group bg-grey5 rounded p-3 p-md-4 ">
        <%= label_tag 'Image de la recette', nil, class: 'font-weight-bold text-secondary mb-0' %>
        <%= file_field_tag :picture %>
      </div>

      <div class="form-row p-3 p-md-4 bg-grey5 rounded mb-3 mb-md-4">
        <p class="font-weight-bold text-secondary mb-4"> Sélectionner les ingrédients qui composent votre recette<p>

        <% @ingredients.sort_by{ |m| m.name.downcase }.each do |ingredient| %>
          <div class="col-12 col-sm-4">
            <%= check_box_tag "ingredient_ids[#{ingredient.id}]", ingredient.id, false, :name => "ingredient_ids[]", class:"mr-2"%>
            <%= ingredient.name %>
          </div>
          <div class="col-12 col-sm-8 mb-3 mb-sm-0">
            <small class="text-grey1 mr-2"><%= label_tag 'Quantité' %></small>
            <%= number_field_tag "quantities[#{ingredient.id}]", class:"form-control" %>
          </div>
          <br>
        <% end %>
      </div>

      <div class="form-group text-center">
        <%= submit_tag "Proposer la recette", class:"btn btn-primary btn-lg" %>
      </div>
    <% end %>

  </div>
</div>

app/views/recipes/show.html.erb
<% content_for(:title, @recipe.name) %>

<div class="bg-container" id="show-recipes">

  <%= render "recipes/recipe_content" %>
  <%= render "recipes/recipe_comments" %>

</div>