config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root 'home#index'
  get 'contact', to: 'single_pages#contact'
  get 'concept', to: 'single_pages#concept'
  get 'team', to: 'single_pages#team'
  
 

  resources :ingredients, only: [:index] 
  resources :menu_recipes, only: [:create, :destroy] do 
    get :autocomplete_recipe_name, :on => :collection
  end

  resources :recipes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get :autocomplete_ingredient_name, :on => :collection
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :pictures, only: [:create, :show]
  end
  
  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :avatars, only: [:create]
    resources :menus, only: [:show, :destroy, :update] do 
      resources :shopping_lists, only: [:show,:create]
    end
  end

  resources :recipe_categories, only: [:show] 

  namespace :admin do 
    resources :recipes, only: [:index, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :comments, only: [:destroy]
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  before_create :default_image
  after_create :send_welcome_email_to_new_user, :send_new_user_email_to_admin, :attribute_menu_to_new_user
  before_save :default_values

  has_many :recipes, through: :comments
  has_many :recipes, through: :likes
  has_many :menus, dependent: :destroy
  has_many :recipes
  has_many :likes, dependent: :destroy
  has_one_attached :avatar

  def send_welcome_email_to_new_user
    UserMailer.welcome_email_to_new_user(self).deliver_now
  end
   
  def send_new_user_email_to_admin
    AdminMailer.new_user_email_to_admin(self).deliver_now
  end

  def default_image
    self.avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'maite.jpg')), filename: 'maite.jpg', content_type: 'image/jpg')
  end 

  def thumbnail
    return self.avatar.variant(resize: '100x100')
  end

  def attribute_menu_to_new_user
    Menu.create!(user_id: User.last.id, number_of_people: 1)
  end

  def find_liked_recipes(likes)
    recipes_ids = []
    likes.each do |like|
      recipes_ids << like.recipe_id
    end 
    recipes =[]
    recipes_ids.each do |id|
      recipes << Recipe.find(id)
    end 
    return recipes
  end

  def default_values
    self.nickname ||= "Utilisateur anonyme"
    self.is_admin ||= false
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :check_if_admin!

  def index
    @users = User.where(is_admin: false).sort
  end

  def edit 
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(update_params)
    
    flash[:success] = " Le profil n°#{@user.id} a bien été mis à jour"
    redirect_to admin_users_path
  end

  def destroy
    @user = User.find(params[:id])
    @recipes = Recipe.where(user_id: params[:id])
    @recipes.each do |recipe|
      recipe.user_id = 2
      recipe.save
    end
    @user.destroy
    flash[:success] = "L'utilisateur a bien été supprimé "
    redirect_to admin_users_path
  end

  private

  def check_if_admin!
    if user_signed_in?
      if current_user.is_admin == false
        flash[:error] = "Accès réservé aux meilleurs cuisiniers !"
        redirect_to root_path
      end
    else
      flash[:error] = "Accès réservé aux meilleurs cuisiniers !"
      redirect_to root_path
    end
  end

  def update_params
    params[:user].permit(:first_name, :last_name, :nickname)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :edit, :update]
  before_action :is_my_profile!
  #layout 'history_menus' /#pour utiliser ce render, les views des menus doivent etre dans un fichier /layouts/menus
  #layout 'favorite_recipes' 

  def show
    @user = User.find(params[:id])
    @menus = Menu.where(user_id: params[:id])
    @likes = Like.where(user_id: params[:id])
    @recipes = @user.find_liked_recipes(@likes)
  end 
   

  def edit 
    @user = User.find(params[:id])
  end 

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end 
  
  private

  def user_params
    user_params = params.require(:user).permit(:first_name, :last_name, :nickname)
  end 

  def is_my_profile!
    if User.find(params[:id]).id != current_user.id
      flash[:error]= "Reste sur ton profil !"
      redirect_to root_path
    end
  end 
end 

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_avatar.html.erb
<div class="avatar-profile d-flex justify-content-center mb-3">
  <%if @user.avatar.attached?%>
    <%= image_tag @user.avatar %>
  <%else%>
    <%= @user.default_image %>
  <%end%>
</div>

app/views/users/_avatar_edit.html.erb
<h3 class="h4"><i class="far fa-image mr-1 mt-3"></i> Changer d'avatar ?</h3>
<p>
  <%= form_tag user_avatars_path(@user), multipart: true do %>
  <%= file_field_tag :avatar %>
  <%= submit_tag "Mettre à jour", class: 'btn btn-outline-primary ml-3' %>
  <% end %>
</p>

app/views/users/_user_edit_infos.html.erb
<div class="col-12 col-md-8">
  <div class="user-content bg-white p-4 p-lg-5 rounded">
    <h2 class="font-weight-normal mb-4"><i class="far fa-edit mr-2"></i> Modifier mes informations de connexion </h2>

    <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
      <%= render "devise/shared/error_messages", resource: resource %>

      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'form-control mb-4' %>
      </div>

      <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
        <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
      <% end %>

      <div class="field">
        <%= f.label 'Nouveau mot de passe' %> <small class="text-grey2">(Laisser vide pour le garder)</small><br />
        <%= f.password_field :password, autocomplete: "new-password", class: 'form-control' %>
        <% if @minimum_password_length %>
          <em class="text-grey2"><%= @minimum_password_length %> caractères minimum</em>
        <% end %>
      </div>

      <div class="field mt-4">
        <%= f.label 'Re-tapez le nouveau mot de passe' %><br />
        <%= f.password_field :password_confirmation, autocomplete: "new-password", class: 'form-control mb-4' %>
      </div>

      <div class="field">
        <%= f.label 'Mot de passe actuel' %> <small class="text-grey2">(Pour valider les changements)</small><br />
        <%= f.password_field :current_password, autocomplete: "current-password", class: 'form-control mb-4' %>
      </div>

      <div class="actions d-flex justify-content-between mb-5">
        <%= f.submit "Valider", class: 'btn btn-primary' %>
      </div>
    <% end %>

    <h3 class="h4"><i class="far fa-trash-alt mr-1 mb-2"></i></i> Supprimer mon compte ?</h3>
    <%= button_to "Confirmer la suppression", @users, data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-outline-grey1' %>

    <div class="text-center">
      <%= link_to 'Retournez à la page de profil', user_path(current_user), class: 'btn btn-outline-secondary mt-5' %>
    </div>

  </div>
</div>

app/views/users/_user_edit_names.html.erb
<div class="col-12 col-md-8">
  <div class="user-content bg-white p-4 p-lg-5 rounded">

    <h3 class="h2 font-weight-normal"><i class="far fa-user mr-1 mb-3"></i> Éditer mon profil</h3>

    <%= form_with model: @user, method: 'PATCH', class: 'mb-3' do |f| %>
      <%= f.label 'Prénom' %>
      <%= f.text_field :first_name, class: 'form-control mb-3', placeholder: @user.first_name %>
      <%= f.label 'Nom' %>
      <%= f.text_field :last_name, class: 'form-control mb-3', placeholder: @user.last_name %>
      <%= f.label 'Pseudo' %>
      <%= f.text_field :nickname, class: 'form-control mb-4', placeholder: @user.nickname %>
      <%= f.submit 'Mettre à jour', class:"btn btn-primary" %>
    <% end %>

    <hr class="bg-grey5">

    <%= render 'avatar_edit'%>
    
    <div class="text-center">
      <%= link_to 'Retournez à la page de profil', user_path(current_user), class: 'btn btn-outline-secondary mt-5' %>
    </div>
  </div>
</div>

app/views/users/_user_sidebar.html.erb
<div class="col-12 col-md-4">
  <div class="user-info bg-white rounded">
    <%= render "users/avatar"%>
    <h4 class="mb-2"><%= @user.first_name %> <%= @user.last_name %></h4>
    <h5 class="h6 text-grey1 mb-0"> <i class="fas fa-at text-grey2"></i> <%= @user.nickname == nil ? "Pseudo" : @user.nickname %></h6>
    <p> <i class="fas fa-envelope text-grey2 mr-2"></i> <%= @user.email%></p>
    <div class="user-links">
      <%= link_to edit_user_path(@user.id) do %>
        <i class="fas fa-user"></i> Éditer mon profil
      <% end %><br>
      <%= link_to edit_user_registration_path(@user) do %>
        <i class="fas fa-lock"></i> Modifier infos connexion
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="bg-container" id="user-profile">
  <div class="block-1000 rounded mx-auto">

    <div class="row">
      <%= render 'users/user_sidebar' %>
      <%= render 'user_edit_names'%>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="bg-container" id="user-profile">
  <div class="block-1000 rounded mx-auto">

    <div class="row">

      <%= render 'user_sidebar' %>

      <div class="col-12 col-md-8">
        <div class="user-content bg-grey5 p-4 p-lg-5">
          <h1 class="mt-3 font-weight-normal mr-1"><i class="far fa-user-circle"></i> Mon profil</h1>
          <p class="intro mb-5">Bienvenue sur votre espace personnel.<br>Retrouvez vos recettes favorites et tous les menus que vous avez composés.<p>
          <%= render "layouts/favorite_recipes"%>
          <%= render "layouts/history_menus" %>
        </div>
      </div>
    </div>

  </div>
</div>