config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  root 'home#index'
  get 'contact', to: 'single_pages#contact'
  get 'concept', to: 'single_pages#concept'
  get 'team', to: 'single_pages#team'
  
 

  resources :ingredients, only: [:index] 
  resources :menu_recipes, only: [:create, :destroy] do 
    get :autocomplete_recipe_name, :on => :collection
  end

  resources :recipes, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    get :autocomplete_ingredient_name, :on => :collection
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
    resources :pictures, only: [:create, :show]
  end
  
  resources :users, only: [:show, :edit, :update, :destroy] do
    resources :avatars, only: [:create]
    resources :menus, only: [:show, :destroy, :update] do 
      resources :shopping_lists, only: [:show,:create]
    end
  end

  resources :recipe_categories, only: [:show] 

  namespace :admin do 
    resources :recipes, only: [:index, :edit, :update, :destroy]
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :comments, only: [:destroy]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :recipe
  belongs_to :user

  validates :description, presence: true
end

app/models/composition.rb
class Composition < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe

  validates :quantity, 
  presence: true,
  numericality: { greater_than: 0 }

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

  belongs_to :ingredient_category
  has_many :compositions
  has_many :recipes, through: :compositions

  validates :name, presence: true, length: { in: 3..50 }
  validates :calories, presence: true, :numericality => { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 999 }

  def funky_method
    "#{self.name}".camelize
  end

end

app/models/like.rb
class Like < ApplicationRecord

  belongs_to :user
  belongs_to :recipe
  
end

app/models/menu.rb
class Menu < ApplicationRecord
  before_save :default_values

  validates :user, presence: true
  validates :number_of_people, presence: true
  

  belongs_to :user
  has_many :menu_recipes, dependent: :destroy
  has_one :shopping_list, dependent: :destroy
  has_many :recipes, through: :menu_recipes
  has_one :shopping_list, dependent: :destroy 
  
  
 
  def default_values
    self.number_of_people ||= 1
  end

end

app/models/menu_recipe.rb
class MenuRecipe < ApplicationRecord
  
  belongs_to :recipe
  belongs_to :menu

end

app/models/menu_user.rb
class MenuUser < ApplicationRecord

  belongs_to :menu
  belongs_to :user
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  before_save :default_values
    
  belongs_to :recipe_category
  belongs_to :user
  has_many :users, through: :likes
  has_many :comments, dependent: :destroy
  has_many :users, through: :comments
  has_many :menu_recipes, dependent: :destroy
  has_many :menus, through: :menu_recipes
  has_many :compositions, dependent: :destroy
  has_many :ingredients, through: :compositions
  has_many :likes, dependent: :destroy
  has_one_attached :picture

  validates :name, presence: true
  validates :description, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :price_indicator, presence: true
  validates :recipe_category_id, presence: true

  before_create :default_picture

  default_scope { order(created_at: :desc) }

  def default_picture
    self.picture.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'default_recipe.jpg')), filename: 'default_recipe.jpg', content_type: 'image/jpg')
  end 
  
  def get_ingredients_number_from_new_recipe_form(params)
    ingredients  = []
    params.each do |ingredient|
      if ingredient != '0'
        ingredients << ingredient.to_i
      end
    end
    return ingredients
  end
  
  def translate_input_ingredients_into_database_ingredients_ids(params)
    selected_ingredients = params.split(', ') # je récupère les ingrédients sélectionnés en splittant à chaque espace
    selected_ingredients_objects = [] # initialisation du tableau qui va contenir les ids d'ingrédients
    selected_ingredients.each do |ingredient_name| # pour chaque nom d'ingrédient entré dans ma barre de recherche
      Ingredient.all.each do |ingredient| # et pour chaque ingrédient présent dans ma BDD
        if ingredient_name == ingredient.name # je compare l'entrée avec les noms
          selected_ingredients_objects << ingredient # s'il existe, j'enregistre l'id
        end
      end
    end
      return selected_ingredients_objects
  end

  def find_recipes_associated_with_ingredients(ingredients)
    all_recipes = Recipe.where(is_displayed: true)
    matching_recipes = []
    all_recipes.each do |recipe|
      if (ingredients - recipe.ingredients).empty? 
        matching_recipes << recipe
      end
    end
    return matching_recipes
  end  

  def picture_300
    return self.picture.variant(resize: '300x300')
  end  

  def default_values
    self.is_displayed ||= false
  end
  
end

app/models/recipe_category.rb
class RecipeCategory < ApplicationRecord

    has_many :recipes


end

app/models/shopping_list.rb
class ShoppingList < ApplicationRecord
  belongs_to :menu

  validates :menu, presence: true
  validates :ingredients_qty, presence: true


  def find_number_of_different_ingredients_in_a_menu(menu)
    menu_recipes = MenuRecipe.where(menu_id: menu.id)
    
    recipes = []
    menu_recipes.each do |menu_recipe|
      recipes << Recipe.find(menu_recipe.recipe_id)
    end

    compositions = []
    recipes.each do |recipe|
      compositions << Composition.where(recipe_id: recipe.id)
    end

    compositions = compositions.flatten

    ingredients = []
    compositions.each do |composition|
      ingredients << Ingredient.find_by(id: composition.ingredient_id)
    end
    recipes.each do |recipe|
    end

    grouped_ingredients = ingredients.group_by(&:id)
    return grouped_ingredients
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  before_create :default_image
  after_create :send_welcome_email_to_new_user, :send_new_user_email_to_admin, :attribute_menu_to_new_user
  before_save :default_values

  has_many :recipes, through: :comments
  has_many :recipes, through: :likes
  has_many :menus, dependent: :destroy
  has_many :recipes
  has_many :likes, dependent: :destroy
  has_one_attached :avatar

  def send_welcome_email_to_new_user
    UserMailer.welcome_email_to_new_user(self).deliver_now
  end
   
  def send_new_user_email_to_admin
    AdminMailer.new_user_email_to_admin(self).deliver_now
  end

  def default_image
    self.avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'maite.jpg')), filename: 'maite.jpg', content_type: 'image/jpg')
  end 

  def thumbnail
    return self.avatar.variant(resize: '100x100')
  end

  def attribute_menu_to_new_user
    Menu.create!(user_id: User.last.id, number_of_people: 1)
  end

  def find_liked_recipes(likes)
    recipes_ids = []
    likes.each do |like|
      recipes_ids << like.recipe_id
    end 
    recipes =[]
    recipes_ids.each do |id|
      recipes << Recipe.find(id)
    end 
    return recipes
  end

  def default_values
    self.nickname ||= "Utilisateur anonyme"
    self.is_admin ||= false
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ingredients_rand = Ingredient.all.sample(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def bootstrap_class_for_flash(type)
    case type
      when 'notice' then "alert-info"
      when 'success' then "alert-success"
      when 'error' then "alert-danger"
      when 'alert' then "alert-warning"
    end
  end
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper

  def is_current_user_the_creator(recipe)
    if user_signed_in?
      if current_user.id == recipe.user_id
        return true
      end
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_concept.html.erb
<section class="bg-grey5">
  <div class="block block-1200">
    <header class="text-center mb-5"> 
      <h3 class="text-secondary"><i class="far fa-lightbulb mr-2"></i> Comment ça marche ? <br> <span class="h4 font-weight-normal">en quelques étapes</span></h3>
    </header>

    <div class="row">

      <div class="col-12 col-sm-6 col-md-4">
        <div class="card p-4 text-center rounded border-0">
          <div class="card-body">
            <h5 class="card-title text-indigo-dark5 h4"><i class="fas fa-user-circle"></i> Créer votre compte utilisateur</h5>
            <p class="card-text text-grey1 h6 font-weight-normal">Avoir un compte vous permet d'accéder à votre menu de batch-cooking</p>
          </div>
        </div>
      </div>
      
      <div class="col-12 col-sm-6 col-md-4">
        <div class="card p-4 text-center rounded border-0">
          <div class="card-body">
            <h5 class="card-title h4"><i class="fas fa-mortar-pestle mr-2"></i> Composer votre menu</h5>
            <p class="card-text text-grey1 h6 font-weight-normal"> Ajoutez des recettes dans votre menu</p>
          </div>
        </div>
      </div>

      <div class="col-12 col-sm-6 col-md-4">
        <div class="card p-4 text-center rounded border-0">
          <div class="card-body">
            <h5 class="card-title h4"><i class="far fa-user-circle"></i> Générer votre liste de course</h5>
            <p class="card-text text-grey1 h6 font-weight-normal">Avoir un compte vous permettra de créer un menu composé de recettes pour réaliser votre batch-cooking.</p>
          </div>
        </div>
      </div>

      

    </div>

  </div>
<section>

app/views/home/_diet_cards.html.erb
<section class="bg-white">
  <div class="block block-1200">
    <header class="text-center mb-4"> 
      <h3 class="text-secondary"><i class="fas fa-mortar-pestle mr-2"></i>Composez votre batch-cooking <br> <span class="h4 font-weight-normal">selon votre régime alimentaire</span></h3>
    </header>
    <div class="row">

      <div class="col-sm-4 mb-3 md-md-0">
        <div class="d-inline-block diet-pic">
          <%= link_to recipe_category_path(id: 3), method: :get do %>
            <%= image_tag("the-creative-exchange-1309304-unsplash", class:"w-100 rounded-top" )%>
          <% end %>
          <h3 class=""><%= link_to "Végétalien", recipe_category_path(id: 3), method: :get, class:"h4 font-weight-normal text-white rounded-bottom text-center py-2 px-4 bg-vegan d-block" %></h3>
        </div>
      </div>

      <div class="col-sm-4 mb-3 md-md-0">
        <div class="d-inline-block">
          <%= link_to recipe_category_path(id: 2), method: :get do %>
            <%= image_tag("brooke-lark-229136-unsplash", class:"w-100 rounded-top" )%>
          <% end %>
          <h3 class=""><%= link_to "Végétarien", recipe_category_path(id: 2), method: :get, class:"h4 font-weight-normal text-white rounded-bottom text-center py-2 px-4 bg-vegetarian d-block" %></h3>
        </div>
      </div>

      <div class="col-sm-4 mb-3 md-md-0">
        <div class="d-inline-block">
        <%= link_to recipe_category_path(id: 1), method: :get, class: 'lol' do %>
          <%= image_tag("mariana-medvedeva-561531-unsplash", class:"w-100 rounded-top" )%>
        <% end %>
          <h3 class=""><%= link_to "Omnivore", recipe_category_path(id: 1), method: :get, class:"h4 font-weight-normal test text-white rounded-bottom text-center py-2 px-4 bg-omnivore d-block" %></h3>
        </div>
      </div>

    </div>
    <footer class="text-center p-3">
      <%= link_to "Voir toutes les recettes", recipes_path, class:"btn btn-outline-primary btn-lg" %>
    </footer>
  </div>
</section>

app/views/home/_ingredients_featured.html.erb
<section class="bg-indigo4">
  <div class="block block-1000">
    <header class="text-center mb-4">
      <h3><i class="far fa-lightbulb"></i> Les 5 ingrédients du moment !</h3>
       <%@ingredients_rand.each do |ingredient|%>
     <h6><div class=ingredient-cloud> <sub><%=ingredient.name%></sub>
     </div>
      <%end%> </h6>
    </header>
    <footer class="text-center">
      <%= link_to "Voir tous les ingrédients disponibles", ingredients_path, class:"btn btn-outline-primary btn-lg" %>
    </footer>
  </div>
</section>

app/views/home/_introduction.html.erb
<section class="bg-dark">
  <div class="block block-900">
    <header class="text-center text-white mb-4">
      <h3 class="text-primary"><i class="far fa-heart mr-2"></i> Bienvenue dans la communauté <br>des Batch Cookerz ! </h3>
    </header>
    <article>
      <p class="h4 text-white text-center font-weight-normal">Le batch cooking, comment ? pour qui ? pourquoi ? <br> Ici se retrouve tous ceux qui aiment cuisiner et manger de bons petits plats. Grace à notre site, vous pourrez cuisiner vos repas pour toute la semaine en quelques heures le week-end.</p>
    </article>
  </div>
</section>

app/views/home/_jumbotron.html.erb
<!-- JUMBOTRON -->
<section class="block d-flex flex-column justify-content-center align-items-center" id="home">
    <header class="text-center block block-1000">
      <h2 class="text-white mb-4 display-2 font-weight-normal">Préparez vos repas une seule fois, <br>et assemblez la semaine !</h2>
      <h3 class="h5 text-white font-weight-normal mb-3">Composez votre batch-cooking en indiquant des ingrédients</h3>
      <div id="search-bar">
        <%= form_tag({:controller => "recipes", :action => "index"}, :method => "get", class:'input-group input-group-lg d-flex justify-content-center') do %>
          <%= autocomplete_field_tag :ingredient, "", 
            autocomplete_ingredient_name_recipes_path, 
            'data-delimiter' => ', ', 
            :multiple => true, 
            :size => 75, 
            'data-noMatchesLabel' => 'Ingrédient non trouvé',
            'data-auto-focus' => true, 
            :append_to => "#proposed_ingredients",
           class: 'form-control w-100 rounded' %>
           <div id="proposed_ingredients">
           </div>
          <div class="text-center mt-4 w-100 block block-500 p-0">
          <div class="row search-buttons">
            <div class="col-12 col-sm-6 pr-md-2 pb-3 pb-sm-0">
              <%= submit_tag 'Recherche', name: nil, class:'w-100 btn btn-primary btn-lg rounded' %>
              
            </div>
            <div class="col-12 col-sm-6 pl-md-2">
              <%= link_to "Toutes les recettes", recipes_path(@recipes), class: 'd-block w-100 btn btn-indigo1 btn-lg' %>
            </div>
          </div>
        <% end %>
      </div>
    </header>
</section>

app/views/home/_recipes_featured.html.erb
<section class="bg-indigo5">
  <div class="block block-1000">
    <header class="text-center mb-4">
      <h3>En manque d'inspiration ?</h3>
      <h3 class="h4 font-weight-normal">Nos recettes du moment</h2>
    </header>
  </div>
</section>

app/views/home/index.html.erb
<%= render 'jumbotron' %>
<%= render 'introduction' %>
<%= render 'diet_cards' %>
<!-- <%= render 'concept' %> -->
<!-- <%= render 'recipes_featured' %> -->
<!-- <%= render 'ingredients_featured' %> -->